/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as EventsEventIdNotificationsRouteImport } from './routes/events/$eventId/notifications'
import { Route as EventsEventIdCheckInRouteImport } from './routes/events/$eventId/check-in'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdNotificationsRoute =
  EventsEventIdNotificationsRouteImport.update({
    id: '/events/$eventId/notifications',
    path: '/events/$eventId/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdCheckInRoute = EventsEventIdCheckInRouteImport.update({
  id: '/events/$eventId/check-in',
  path: '/events/$eventId/check-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/events': typeof EventsIndexRoute
  '/events/$eventId/check-in': typeof EventsEventIdCheckInRoute
  '/events/$eventId/notifications': typeof EventsEventIdNotificationsRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/events': typeof EventsIndexRoute
  '/events/$eventId/check-in': typeof EventsEventIdCheckInRoute
  '/events/$eventId/notifications': typeof EventsEventIdNotificationsRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventId/check-in': typeof EventsEventIdCheckInRoute
  '/events/$eventId/notifications': typeof EventsEventIdNotificationsRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/notifications'
    | '/profile'
    | '/events'
    | '/events/$eventId/check-in'
    | '/events/$eventId/notifications'
    | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/notifications'
    | '/profile'
    | '/events'
    | '/events/$eventId/check-in'
    | '/events/$eventId/notifications'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/notifications'
    | '/profile'
    | '/events/'
    | '/events/$eventId/check-in'
    | '/events/$eventId/notifications'
    | '/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsEventIdCheckInRoute: typeof EventsEventIdCheckInRoute
  EventsEventIdNotificationsRoute: typeof EventsEventIdNotificationsRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/notifications': {
      id: '/events/$eventId/notifications'
      path: '/events/$eventId/notifications'
      fullPath: '/events/$eventId/notifications'
      preLoaderRoute: typeof EventsEventIdNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/check-in': {
      id: '/events/$eventId/check-in'
      path: '/events/$eventId/check-in'
      fullPath: '/events/$eventId/check-in'
      preLoaderRoute: typeof EventsEventIdCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsEventIdCheckInRoute: EventsEventIdCheckInRoute,
  EventsEventIdNotificationsRoute: EventsEventIdNotificationsRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
